name: Update Housing Data

on:
  schedule:
    # Run daily at 6 AM UTC (7 AM BST, 6 AM GMT)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.verify-changed-files.outputs.changed }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Update housing data
      run: |
        python scripts/update_data.py
      env:
        # Add any API keys here as secrets
        # LAND_REGISTRY_API_KEY: ${{ secrets.LAND_REGISTRY_API_KEY }}
        # ONS_API_KEY: ${{ secrets.ONS_API_KEY }}

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit updated data
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/*.csv public/*.json
        git commit -m "🏠 Update housing affordability data - $(date +'%Y-%m-%d')"
        git push

    - name: Setup Node.js
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: pnpm install

    - name: Build application
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: pnpm build

    - name: Setup Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: actions/configure-pages@v4

    - name: Upload artifact
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  # Deploy job - only runs if data was updated
  deploy:
    if: needs.update-data.outputs.changed == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-data
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 